version: '3'
services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    links:
      - mongo
    ports:
      - '127.0.0.1:8888:8888'

  mongo:
    image: mongo:2.6.11
    ports:
      - '127.0.0.1:27017:27017'
    expose:
      - '27017'